#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
// TODO: Test if this function is properly adapted to be called from C...
void RotateVector(S32 norme, S32 alpha, S32 beta, S32 gamma);

// =============================================================================
#ifdef __cplusplus
}
#endif
