#include <3D/DATAMAT.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
TYPE_MAT MatriceWorld;
TYPE_MAT MatrixLib1;
TYPE_MAT MatrixLib2;
TYPE_MAT MatriceRot;

// =============================================================================
#ifdef __cplusplus
}
#endif
