#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
extern S32 CalcGraphMsk(S32 numbrick, U8 *bankbrick, U8 *ptmask);

// =============================================================================
#ifdef __cplusplus
}
#endif
