#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
S32 CopyMask(S32 nummask, S32 x, S32 y, void *bankmask, void *src);

// =============================================================================
#ifdef __cplusplus
}
#endif
