#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
extern S32 ScreenXMin;
extern S32 ScreenYMin;
extern S32 ScreenXMax;
extern S32 ScreenYMax;

// =============================================================================
#ifdef __cplusplus
}
#endif
