#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
// Comes from GLOBEXT.CPP and is non C
extern U8 *ScreenAux;

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
void InitAdeline(S32 argc, char *argv[]);

// =============================================================================
#ifdef __cplusplus
}
#endif
