
#pragma once
#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

S32 Filler_TextureGouraud(U32 nbLines, U32 fillCurXMin, U32 fillCurXMax);
S32 Filler_TextureGouraudNZW(U32 nbLines, U32 fillCurXMin, U32 fillCurXMax);

// =============================================================================
#ifdef __cplusplus
}
#endif
