#pragma once

#include <POLYGON/POLY.H>
#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
extern S32 TestVuePoly(Struc_Point *ptr);

// =============================================================================
#ifdef __cplusplus
}
#endif
