#!/usr/bin/env python3
"""Generate the index of control-harness fixtures, or check the committed one is current.

`tests/automation` holds the only tests that drive a real engine, and they cannot run in CI: every
one of them calls `precheck`, which requires retail game data. `run.sh` exits 0 on skips by design,
so wiring the suite into a workflow would produce a permanently green check that ran nothing.

What *can* be checked without game data is that the list is honest. It was not: the roadmap quoted
60 fixtures in two places, FEATURE_WORKFLOW quoted 59, and there were 62. A number retyped into
prose drifts the moment a fixture lands, and the drift is invisible because nothing reads it.

So the index is generated from the fixtures themselves. Every one opens with a `#` summary on line
2 and sets `TESTNAME`, which is enough to build the table without a hand-maintained list to forget.
`--check` fails when the committed copy has drifted, and runs in `format.yml` beside check-arch.py,
needing no toolchain and no data.

The last-run record is deliberately a separate file. Putting a timestamp in here would mean every
local run dirties the file this check compares, and the check would fail for the wrong reason.

  scripts/ci/gen-automation-index.py            # rewrite tests/automation/README.md
  scripts/ci/gen-automation-index.py --check    # fail if it is out of date (what CI runs)
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SUITE = os.path.join(ROOT, "tests", "automation")
INDEX = os.path.join(SUITE, "README.md")
RUN_RECORD = "last-run.md"

# Helpers a fixture calls when it needs more than a binary, data and a display.
EXTRA = (
    ("need_save", "save fixture"),
    ("have_voice", "voice data"),
    ("ui_compare", "UI goldens"),
)

HEADER = """<!-- Generated by scripts/ci/gen-automation-index.py. Do not edit by hand.
     Run `make automation-index` after adding or renaming a fixture. -->

# Control-harness fixtures

The only tests here that drive a real engine. They need a built binary, retail game data
(`LBA2_GAME_DIR`) and a display, so **no workflow runs them** and none can: `run.sh` reports a
missing prerequisite as SKIP and exits 0, so a CI job would go green having run nothing.

That makes them the one body of coverage this repo can quote without checking. This index is
generated from the fixtures so at least the list cannot drift, and
[{record}]({record}) records what happened the last time somebody ran them.

```bash
LBA2_GAME_DIR=/path/to/data tests/automation/run.sh     # the whole suite
LBA2_GAME_DIR=/path/to/data bash tests/automation/test_cli_contract.sh   # one fixture
```

Attaching the run record to a PR that touches engine behaviour is the cheapest way to show the
suite still passes, since CI cannot say so.

"""


def summary(path):
    """The fixture's own one-line description: the comment block under the shebang."""
    with open(path, encoding="utf-8") as fh:
        lines = fh.read().splitlines()
    out = []
    for line in lines[1:]:
        if not line.startswith("#"):
            break
        text = line.lstrip("#").strip()
        if not text:
            break
        out.append(text)
    joined = " ".join(out)
    # First sentence, so a long rationale paragraph does not become a table cell.
    m = re.search(r"^(.+?[.!?])(\s|$)", joined)
    text = (m.group(1) if m else joined).strip()
    return text.replace("|", r"\|")


def requirements(path):
    with open(path, encoding="utf-8") as fh:
        body = fh.read()
    return [label for call, label in EXTRA if call in body]


def build():
    names = sorted(
        f for f in os.listdir(SUITE) if f.startswith("test_") and f.endswith(".sh")
    )
    rows = []
    for name in names:
        path = os.path.join(SUITE, name)
        extra = requirements(path)
        rows.append((name, summary(path), ", ".join(extra) if extra else "-"))

    parts = [HEADER.format(record=RUN_RECORD)]
    parts.append(f"{len(rows)} fixtures.\n\n")
    parts.append("| Fixture | What it pins | Also needs |\n|---|---|---|\n")
    for name, text, extra in rows:
        parts.append(f"| [{name}]({name}) | {text} | {extra} |\n")
    return "".join(parts)


def main(argv):
    if not os.path.isdir(SUITE):
        print(f"error: {SUITE} not found", file=sys.stderr)
        return 1
    generated = build()

    if "--check" in argv:
        if not os.path.exists(INDEX):
            print(f"error: {os.path.relpath(INDEX, ROOT)} is missing. "
                  "Run `make automation-index`.", file=sys.stderr)
            return 1
        with open(INDEX, encoding="utf-8") as fh:
            current = fh.read()
        if current != generated:
            print(f"error: {os.path.relpath(INDEX, ROOT)} is out of date. "
                  "A fixture was added, renamed or had its summary edited.\n"
                  "       Run `make automation-index` and commit the result.", file=sys.stderr)
            return 1
        n = generated.count("\n| [test_")
        print(f"automation index: current, {n} fixtures")
        return 0

    with open(INDEX, "w", encoding="utf-8") as fh:
        fh.write(generated)
    print(f"wrote {os.path.relpath(INDEX, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
