//──────────────────────────────────────────────────────────────────────────
#ifndef	LIB_SVGA
#define	LIB_SVGA

//──────────────────────────────────────────────────────────────────────────
#include <SYSTEM/ADELINE.H>

//──────────────────────────────────────────────────────────────────────────
#include <POLYGON.H>

//──────────────────────────────────────────────────────────────────────────
#include <SVGA/SCREENXY.H>
#include <SVGA/COPYBOX.H>
#include <SVGA/COPYBOV.H>
#include <SVGA/BLITBOX.H>
#include <SVGA/BLITBOV.H>
#include <SVGA/CLRBOX.H>
#include <SVGA/CLEABOV.H>
#include <SVGA/DIRTYBOX.H>
#include <SVGA/VESA.H>
#include <SVGA/DDRAW.H>
#include <SVGA/AFFSTR.H>
#include <SVGA/MASK.H>
#include <SVGA/CALCMASK.H>
#include <SVGA/COPYMASK.H>
#include <SVGA/GRAPH.H>
#include <SVGA/FONT.H>
#include <SVGA/GPRINTF.H>
#include <SVGA/CLIP.H>
#include <SVGA/SHADE.H>
#include <SVGA/CPYBLOCK.H>
#include <SVGA/CPYBLOCI.H>
#include <SVGA/RESBLOCK.H>
#include <SVGA/SAVBLOCK.H>
#include <SVGA/BOX.H>
#include <SVGA/FIL_LINE.H>
#include <SVGA/RECT.H>
#include <SVGA/PLOT.H>
#include <SVGA/SCALEBOX.H>
#include <SVGA/SCALESPT.H>
#include <SVGA/SCALESPI.H>
#include <SVGA/PAL.H>

//──────────────────────────────────────────────────────────────────────────
#endif//LIB_SVGA

//──────────────────────────────────────────────────────────────────────────
