#!/usr/bin/env python3
"""
Emit a single C source file with const byte arrays (and size constants) for
embedding binary blobs (e.g. 640x480 LIM + 768-byte PAL) into the lba2 binary.

Usage:
  python3 tools/bin2c.py -o out.c \
      g_MyBlob:path/to/file.lim \
      g_Other:path/to/file.pal
"""

from __future__ import annotations

import argparse
from pathlib import Path


def emit_c_array(name: str, data: bytes) -> str:
    lines = [f"const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {hexes},")
    lines.append("};")
    lines.append(f"const unsigned int {name}Size = {len(data)}u;")
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "-o",
        "--output",
        type=Path,
        required=True,
        help="Output .c file path",
    )
    p.add_argument(
        "blobs",
        metavar="NAME:FILE",
        nargs="+",
        help="C symbol name and input path, e.g. g_Foo:./foo.bin",
    )
    args = p.parse_args()

    parts: list[str] = [
        "/* Generated by tools/bin2c.py — do not edit. */",
        "",
    ]
    for spec in args.blobs:
        if ":" not in spec:
            raise SystemExit(f"Invalid blob spec (expected NAME:path): {spec!r}")
        name, fpath = spec.split(":", 1)
        path = Path(fpath)
        if not path.is_file():
            raise SystemExit(f"Missing file for {name}: {path}")
        data = path.read_bytes()
        parts.append(emit_c_array(name, data))
        parts.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(parts) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
