# Resolve the engine version string and write it to two artifacts in the
# build tree. Invoked via `cmake -P` from add_custom_command (build time)
# and from execute_process (configure time, to seed the header before the
# first build step runs).
#
# Inputs (passed via -D from the caller):
#   SOURCE_DIR        — repo root (where VERSION lives and .git may live)
#   OUT_TXT           — path to write plain-text version (build/VERSION.txt)
#   OUT_HDR           — path to write generated header (build/VERSION_GENERATED.h)
#   GIT_EXECUTABLE    — full path to `git`, or empty if not found
#
# Source of truth: the `VERSION` file at the repo root (Plan C — checked-in
# canonical value). Git is used only to mark a dirty working tree, so:
#
#   * Tarballs / no-git environments    → exact contents of VERSION
#   * Clean dev clone                    → exact contents of VERSION
#   * Dirty dev clone (uncommitted)      → VERSION contents + "-dirty"
#
# This avoids fetch-depth concerns (no `git describe`, no tag history needed)
# and keeps maintainer intent (VERSION file) authoritative — git only
# enriches the bit it can know without history: "do you have uncommitted
# changes?".

# Read VERSION file (canonical source).
if(NOT EXISTS "${SOURCE_DIR}/VERSION")
    message(FATAL_ERROR "VERSION file missing at ${SOURCE_DIR}/VERSION")
endif()
file(READ "${SOURCE_DIR}/VERSION" _version_raw)
string(STRIP "${_version_raw}" _version)

if(_version STREQUAL "")
    message(FATAL_ERROR "VERSION file is empty")
endif()

# Optional git enrichment: append "-dirty" if working tree has uncommitted
# changes. Skip silently if git isn't available or .git is missing
# (tarball case).
if(GIT_EXECUTABLE AND EXISTS "${SOURCE_DIR}/.git")
    execute_process(
        COMMAND ${GIT_EXECUTABLE} diff-index --quiet HEAD --
        WORKING_DIRECTORY ${SOURCE_DIR}
        RESULT_VARIABLE _git_dirty_rc
        OUTPUT_QUIET
        ERROR_QUIET
    )
    # diff-index returns 0 if clean, 1 if dirty, other on error.
    if(_git_dirty_rc EQUAL 1)
        # Don't double-suffix if VERSION already ends in "-dirty".
        if(NOT _version MATCHES "-dirty$")
            set(_version "${_version}-dirty")
        endif()
    endif()
endif()

# The commit the build came from, so a log or crash report names the exact source
# even when every rolling build carries the same VERSION. "unknown" without git.
set(_commit "unknown")
if(GIT_EXECUTABLE AND EXISTS "${SOURCE_DIR}/.git")
    execute_process(
        COMMAND ${GIT_EXECUTABLE} rev-parse --short=12 HEAD
        WORKING_DIRECTORY ${SOURCE_DIR}
        RESULT_VARIABLE _git_commit_rc
        OUTPUT_VARIABLE _git_commit
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
    if(_git_commit_rc EQUAL 0 AND NOT _git_commit STREQUAL "")
        set(_commit "${_git_commit}")
    endif()
endif()

# Header content. C++98-clean: plain #defines.
set(_hdr_content "/* Generated by cmake/write_version.cmake — do not edit. */\n#define LBA2_VERSION_STRING \"${_version}\"\n#define LBA2_COMMIT_STRING \"${_commit}\"\n")

# Write only when contents change. This keeps timestamps stable across builds
# where the version didn't move, so VERSION.CPP doesn't recompile every time.
set(_existing_hdr "")
if(EXISTS "${OUT_HDR}")
    file(READ "${OUT_HDR}" _existing_hdr)
endif()
if(NOT "${_existing_hdr}" STREQUAL "${_hdr_content}")
    file(WRITE "${OUT_HDR}" "${_hdr_content}")
endif()

set(_txt_content "${_version}\n")
set(_existing_txt "")
if(EXISTS "${OUT_TXT}")
    file(READ "${OUT_TXT}" _existing_txt)
endif()
if(NOT "${_existing_txt}" STREQUAL "${_txt_content}")
    file(WRITE "${OUT_TXT}" "${_txt_content}")
endif()
