name: Linux
on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install SDL3
        uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 3-latest

      - name: Install UASM
        uses: supplypike/setup-bin@v3
        with:
          uri: 'https://github.com/Terraspace/UASM/releases/download/v2.57r/uasm257_linux64.zip'
          name: 'uasm'
          version: '2.57'

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Run CMake
        run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} --preset linux

      - name: Build
        run: cmake --build ${{github.workspace}}/build --target lba2
